name: Translation
description: Provide a translation for in-game strings.
title: 'Translation: '
labels:
  - enhancement
  - translation
assignees:
  - p3lim
body:
  - type: dropdown
    id: locale
    attributes:
      label: Which locale are these translations for?
      options:
        - deDE (German)
        - esES (Spanish, Spain)
        - esMX (Spanish, Mexico)
        - frFR (French)
        - itIT (Italian)
        - koKR (Korean)
        - ptBR (Portuguese, Brazil)
        - ruRU (Russian)
        - zhCN (Chinese, Simplified, PRC)
        - zhTW (Chinese, Traditional, Taiwan)
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please translate each sentence below into the fields next to them.  
        It is not required to translate all of them.

        ---
# the rest is a list of strings to translate
  - type: input
    attributes:
      label: '"Change maps"'
      description: This is used in the settings.
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Change to the most appropriate map.\n\n|cffff0000Warning:|r This may cause errors!"'
      description: This is used in the settings. '\n', '|cffff0000' and '|r' is formatting.
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Map pin scale"'
      description: This is used in the settings.
      placeholder: Translation here
  - type: input
    attributes:
      label: '"The scale of pins on the map"'
      description: This is used in the settings.
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Pin size zoom factor"'
      description: This is used in the settings.
      placeholder: Translation here
  - type: input
    attributes:
      label: '"How much extra scale to apply when map is zoomed"'
      description: This is used in the settings.
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Taxi world map"'
      description: This is used in the settings.
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Use the normal world map for taxi"'
      description: This is used in the settings.
      placeholder: Translation here
