name: Scrape retail

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths:
      - 'scripts/**.py'
      - '.github/workflows/scrape.yaml'
      - '.github/workflows/scrape_retail.yaml'
  schedule:
    - cron: '0 8 * * 1' # monday morning
  workflow_dispatch:

jobs:
  scrape:
    uses: ./.github/workflows/scrape.yaml
    with:
      flavor: retail
      dbc: wow_latest
      files: |
        dungeons: data/dungeons
